### ISSUE TITLE
Model diff. types of stress

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/hortiprimed#10]
Salt, chlorine, heat 
should each have a model? 

Salt is cheap but heat requires a massive chamber etc.

**Comment by SHMooon** [comment]
the model with salt and heat is created. 

question  
- [ ] do we need a model with chlorine?

**Comment by JBSLutum** [comment]
> the model with salt and heat is created.
> 
> question
> 
>     * [ ]  do we need a model with chlorine?

don't think its necessary for now. if it is relevant it is added fast (I guess... if the rest of the model is working fine)
