### ISSUE TITLE
Data from Geisenheim

### ISSUE THREAD

**Issue by CWWhitney** [CWWhitney/hortiprimed#11]
KW, Co2, Electro

**Comment by SHMooon** [comment]
ask an appointment to Geisenheim to get some Information that we need

**Comment by SHMooon** [comment]
Email form Geisenheim (03.01. & 04.01.2024)

Climate chamber: 

- 5.9 kWh
- 141.6 kW/day 
- for Priming 2 weeks (14 days) 
- They use 4 climate chamber
- around 154 plants (without failure) per climate chamber 

Compare the Germinate between with and without priming direct after heat priming
-  no differences. In fact, over 98% germination always occurred. 
- The heat priming therefore did not lead to poorer germination, but only to a temporary delay in growth and development.
