### ISSUE TITLE
Some error when reading in values

### ISSUE THREAD

**Issue by JBSLutum** [CWWhitney/hortiprimed#6]
Noticed that the NPV at the end is high negative. Think the reason is that "Leistungen" is way to low.

In the picture: left is the code, middle is the .csv with "leistungen" around 700k, right are the variables after "make variables" and "Leistungen" ist just around 0.1.

![grafik](https://github.com/CWWhitney/hortiprimed/assets/58811072/d47b8d2c-9abe-4074-b44e-fe37f2d70c14)

**Comment by CWWhitney** [comment]
We might want to change 'norm' to 'posnorm'

**Comment by SHMooon** [comment]
<img width="509" alt="스크린샷 2023-11-13 07 17 22" src="https://github.com/CWWhitney/hortiprimed/assets/133058568/009b18eb-b2bf-41e0-86d2-6b34c8c55544">


I don't had that problem. 
and I changed 'norm' to 'posnorm'

**Comment by CWWhitney** [comment]
Seems to have been fixed with the posnorm solution
